steps:
- id: 'build'
  name: gcr.io/cloud-builders/mvn
  entrypoint: bash
  args:
  - '-eo'
  - 'pipefail'
  - '-c'
  - 'mvn install' 
options:
  pool:
    name: 'projects/csa-app-dev-0ad127af/locations/me-central1/workerPools/hello-world-me-central1'

