steps:
- id: 'build'
  name: gcr.io/cloud-builders/mvn
  entrypoint: bash
  args:
  - '-eo'
  - 'pipefail'
  - '-c'
  - 'mvn install' 
options:
  pool:
    name: 'projects/[PROJECT_ID]/locations/asia-northeast1/workerPools/hello-world-asia-northeast1-pool'

